// Import the rendercv function and all the refactored components
#import "@preview/rendercv:0.1.0": *

// Apply the rendercv template with custom configuration
#show: rendercv.with(
  name: "{{ cv.name }}",
  footer: context { [#emph[{{ cv.name }} -- #str(here().page())\/#str(counter(page).final().first())]] },
  top-note: [ #emph[Last updated in {{ settings.current_date.strftime('%b %Y') }}] ],
  locale-catalog-language: "{{ locale.language_iso_639_1|default('en') }}",
  page-size: "{{ design.page.size }}",
  page-top-margin: {{ design.page.top_margin }},
  page-bottom-margin: {{ design.page.bottom_margin }},
  page-left-margin: {{ design.page.left_margin }},
  page-right-margin: {{ design.page.right_margin }},
  page-show-footer: {{ design.page.show_footer|default(true)|lower }},
  page-show-top-note: {{ design.page.show_top_note|default(true)|lower }},
  colors-body: {% if design.colors.body %}{{ design.colors.body.as_rgb() }}{% else %}rgb(0, 0, 0){% endif %},
  colors-name: {{ design.colors.name.as_rgb() }},
  colors-headline: {% if design.colors.headline %}{{ design.colors.headline.as_rgb() }}{% else %}{{ design.colors.name.as_rgb() }}{% endif %},
  colors-connections: {{ design.colors.connections.as_rgb() }},
  colors-section-titles: {{ design.colors.section_titles.as_rgb() }},
  colors-links: {{ design.colors.links.as_rgb() }},
  colors-footer: {% if design.colors.footer %}{{ design.colors.footer.as_rgb() }}{% else %}rgb(128, 128, 128){% endif %},
  colors-top-note: {% if design.colors.top_note %}{{ design.colors.top_note.as_rgb() }}{% else %}rgb(128, 128, 128){% endif %},
  typography-line-spacing: {% if design.typography.line_spacing %}{{ design.typography.line_spacing }}{% else %}0.6em{% endif %},
  typography-alignment: "{% if design.typography.alignment %}{{ design.typography.alignment }}{% else %}justified{% endif %}",
  typography-date-and-location-column-alignment: {% if design.typography.date_and_location_column_alignment %}{{ design.typography.date_and_location_column_alignment }}{% else %}right{% endif %},
  typography-font-family-body: "{% if design.typography.font_family.body %}{{ design.typography.font_family.body }}{% else %}Raleway{% endif %}",
  typography-font-family-name: "{% if design.typography.font_family.name %}{{ design.typography.font_family.name }}{% elif design.header.name_font_family %}{{ design.header.name_font_family }}{% else %}Raleway{% endif %}",
  typography-font-family-headline: "{% if design.typography.font_family.headline %}{{ design.typography.font_family.headline }}{% elif design.header.name_font_family %}{{ design.header.name_font_family }}{% else %}Raleway{% endif %}",
  typography-font-family-connections: "{% if design.typography.font_family.connections %}{{ design.typography.font_family.connections }}{% elif design.header.connections_font_family %}{{ design.header.connections_font_family }}{% else %}Raleway{% endif %}",
  typography-font-family-section-titles: "{% if design.typography.font_family.section_titles %}{{ design.typography.font_family.section_titles }}{% elif design.section_titles.font_family %}{{ design.section_titles.font_family }}{% else %}Raleway{% endif %}",
  typography-font-size-body: {% if design.typography.font_size.body %}{{ design.typography.font_size.body }}{% else %}0.9em{% endif %},
  typography-font-size-name: {% if design.typography.font_size.name %}{{ design.typography.font_size.name }}{% elif design.header.name_font_size %}{{ design.header.name_font_size }}{% else %}2.0em{% endif %},
  typography-font-size-headline: {% if design.typography.font_size.headline %}{{ design.typography.font_size.headline }}{% elif design.header.name_font_size %}{{ design.header.name_font_size }}{% else %}1.0em{% endif %},
  typography-font-size-connections: {% if design.typography.font_size.connections %}{{ design.typography.font_size.connections }}{% elif design.header.connections_font_size %}{{ design.header.connections_font_size }}{% else %}0.85em{% endif %},
  typography-font-size-section-titles: {% if design.typography.font_size.section_titles %}{{ design.typography.font_size.section_titles }}{% elif design.section_titles.font_size %}{{ design.section_titles.font_size }}{% else %}1.3em{% endif %},
  typography-small-caps-name: {% if design.typography.small_caps.name %}{{ design.typography.small_caps.name|lower }}{% elif design.header.small_caps_for_name %}{{ design.header.small_caps_for_name|lower }}{% else %}false{% endif %},
  typography-small-caps-headline: {% if design.typography.small_caps.headline %}{{ design.typography.small_caps.headline|lower }}{% else %}false{% endif %},
  typography-small-caps-connections: {% if design.typography.small_caps.connections %}{{ design.typography.small_caps.connections|lower }}{% else %}false{% endif %},
  typography-small-caps-section-titles: {% if design.typography.small_caps.section_titles %}{{ design.typography.small_caps.section_titles|lower }}{% elif design.section_titles.small_caps %}{{ design.section_titles.small_caps|lower }}{% else %}false{% endif %},
  typography-bold-name: {% if design.typography.bold.name %}{{ design.typography.bold.name|lower }}{% elif design.header.name_bold %}{{ design.header.name_bold|lower }}{% else %}false{% endif %},
  typography-bold-headline: {% if design.typography.bold.headline %}{{ design.typography.bold.headline|lower }}{% else %}false{% endif %},
  typography-bold-connections: {% if design.typography.bold.connections %}{{ design.typography.bold.connections|lower }}{% else %}false{% endif %},
  typography-bold-section-titles: {% if design.typography.bold.section_titles %}{{ design.typography.bold.section_titles|lower }}{% elif design.section_titles.bold %}{{ design.section_titles.bold|lower }}{% else %}false{% endif %},
  links-underline: {{ design.links.underline|lower }},
  links-show-external-link-icon: {% if design.links.show_external_link_icon %}{{ design.links.show_external_link_icon|lower }}{% else %}false{% endif %},
  header-alignment: {{ design.header.alignment }},
  header-photo-width: {{ design.header.photo_width }},
  header-space-below-name: {% if design.header.space_below_name %}{{ design.header.space_below_name }}{% elif design.header.vertical_space_between_name_and_connections %}{{ design.header.vertical_space_between_name_and_connections }}{% else %}0.3cm{% endif %},
  header-space-below-headline: {% if design.header.space_below_headline %}{{ design.header.space_below_headline }}{% else %}0.3cm{% endif %},
  header-space-below-connections: {% if design.header.space_below_connections %}{{ design.header.space_below_connections }}{% elif design.header.vertical_space_between_connections_and_first_section %}{{ design.header.vertical_space_between_connections_and_first_section }}{% else %}1.0cm{% endif %},
  header-connections-hyperlink: {% if design.header.connections.hyperlink %}{{ design.header.connections.hyperlink|lower }}{% else %}true{% endif %},
  header-connections-show-icons: {% if design.header.connections.show_icons %}{{ design.header.connections.show_icons|lower }}{% elif design.header.use_icons_for_connections %}{{ design.header.use_icons_for_connections|lower }}{% else %}false{% endif %},
  header-connections-display-urls-instead-of-usernames: {% if design.header.connections.display_urls_instead_of_usernames %}{{ design.header.connections.display_urls_instead_of_usernames|lower }}{% else %}false{% endif %},
  header-connections-separator: "{% if design.header.connections.separator %}{{ design.header.connections.separator }}{% elif design.header.separator_between_connections %}{{ design.header.separator_between_connections }}{% else %}|{% endif %}",
  header-connections-space-between-connections: {% if design.header.connections.space_between_connections %}{{ design.header.connections.space_between_connections }}{% elif design.header.horizontal_space_between_connections %}{{ design.header.horizontal_space_between_connections }}{% else %}0.3cm{% endif %},
  section-titles-type: "{{ design.section_titles.type }}",
  section-titles-line-thickness: {{ design.section_titles.line_thickness }},
  section-titles-space-above: {% if design.section_titles.space_above %}{{ design.section_titles.space_above }}{% elif design.section_titles.vertical_space_above %}{{ design.section_titles.vertical_space_above }}{% else %}0.5cm{% endif %},
  section-titles-space-below: {% if design.section_titles.space_below %}{{ design.section_titles.space_below }}{% elif design.section_titles.vertical_space_below %}{{ design.section_titles.vertical_space_below }}{% else %}0.3cm{% endif %},
  sections-allow-page-break: {% if design.sections.allow_page_break %}{{ design.sections.allow_page_break|lower }}{% elif design.entries.allow_page_break_in_sections %}{{ design.entries.allow_page_break_in_sections|lower }}{% else %}true{% endif %},
  sections-space-between-text-based-entries: {% if design.sections.space_between_text_based_entries %}{{ design.sections.space_between_text_based_entries }}{% else %}0.3em{% endif %},
  sections-space-between-regular-entries: {% if design.sections.space_between_regular_entries %}{{ design.sections.space_between_regular_entries }}{% elif design.entries.vertical_space_between_entries %}{{ design.entries.vertical_space_between_entries }}{% else %}1.2em{% endif %},
  entries-date-and-location-width: {{ design.entries.date_and_location_width }},
  entries-side-space: {% if design.entries.side_space %}{{ design.entries.side_space }}{% elif design.entries.left_and_right_margin %}{{ design.entries.left_and_right_margin }}{% else %}0.2cm{% endif %},
  entries-space-between-columns: {% if design.entries.space_between_columns %}{{ design.entries.space_between_columns }}{% elif design.entries.horizontal_space_between_columns %}{{ design.entries.horizontal_space_between_columns }}{% else %}0.1cm{% endif %},
  entries-allow-page-break: {% if design.entries.allow_page_break %}{{ design.entries.allow_page_break|lower }}{% elif design.entries.allow_page_break_in_entries %}{{ design.entries.allow_page_break_in_entries|lower }}{% else %}false{% endif %},
  entries-short-second-row: {{ design.entries.short_second_row|lower }},
  entries-summary-space-left: {% if design.entries.summary.space_left %}{{ design.entries.summary.space_left }}{% elif design.highlights.summary_left_margin %}{{ design.highlights.summary_left_margin }}{% else %}0cm{% endif %},
  entries-summary-space-above: {% if design.entries.summary.space_above %}{{ design.entries.summary.space_above }}{% elif design.highlights.top_margin %}{{ design.highlights.top_margin }}{% else %}0.12cm{% endif %},
  entries-highlights-bullet: {% if design.entries.highlights.bullet == "●" %} text(13pt, [•], baseline: -0.6pt) {% else %} "{% if design.entries.highlights.bullet %}{{ design.entries.highlights.bullet }}{% elif design.highlights.bullet %}{{ design.highlights.bullet }}{% else %}•{% endif %}" {% endif %},
  entries-highlights-nested-bullet: {% if design.entries.highlights.nested_bullet == "●" %} text(13pt, [•], baseline: -0.6pt) {% else %} "{% if design.entries.highlights.nested_bullet %}{{ design.entries.highlights.nested_bullet }}{% elif design.highlights.bullet %}{{ design.highlights.bullet }}{% else %}•{% endif %}" {% endif %},
  entries-highlights-space-left: {% if design.entries.highlights.space_left %}{{ design.entries.highlights.space_left }}{% elif design.highlights.left_margin %}{{ design.highlights.left_margin }}{% else %}0cm{% endif %},
  entries-highlights-space-above: {% if design.entries.highlights.space_above %}{{ design.entries.highlights.space_above }}{% elif design.highlights.top_margin %}{{ design.highlights.top_margin }}{% else %}0.12cm{% endif %},
  entries-highlights-space-between-items: {% if design.entries.highlights.space_between_items %}{{ design.entries.highlights.space_between_items }}{% elif design.highlights.vertical_space_between_highlights %}{{ design.highlights.vertical_space_between_highlights }}{% else %}0.12cm{% endif %},
  entries-highlights-space-between-bullet-and-text: {% if design.entries.highlights.space_between_bullet_and_text %}{{ design.entries.highlights.space_between_bullet_and_text }}{% elif design.highlights.horizontal_space_between_bullet_and_highlight %}{{ design.highlights.horizontal_space_between_bullet_and_highlight }}{% else %}0.5em{% endif %},
  date: datetime(
    year: {{ settings.current_date.year }},
    month: {{ settings.current_date.month }},
    day: {{ settings.current_date.day }},
  ),
)
